name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up the necessary language/tool version (e.g., Node.js, Java, .NET)
    - name: Set up Node.js (if using Node)
      uses: actions/setup-node@v3
      with:
        node-version: '14' # Use whatever version is applicable to your project

    # Step 3: Install dependencies (if applicable)
    - name: Install dependencies
      run: npm install

    # Step 4: Run your tests
    - name: Run tests
      run: npm test

    # Step 5: Build your project
    - name: Build project
      run: npm run build

    # Step 6: Upload build artifacts (if needed)
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: ./build # Path to the build directory

    # Optional: Build and push a Docker image (if applicable)
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      run: |
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REPOSITORY:$IMAGE_TAG
